name: Beta Preview

on:
  push:
    branches:
      - beta

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Beta Preview
        run: |
          echo "Beta preview build running"
