name: Dev Preview

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Dev Preview
        run: |
          echo "Dev preview build running"
